/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Food } from "./Food";
import { FoodCountArgs } from "./FoodCountArgs";
import { FoodFindManyArgs } from "./FoodFindManyArgs";
import { FoodFindUniqueArgs } from "./FoodFindUniqueArgs";
import { CreateFoodArgs } from "./CreateFoodArgs";
import { UpdateFoodArgs } from "./UpdateFoodArgs";
import { DeleteFoodArgs } from "./DeleteFoodArgs";
import { CartFindManyArgs } from "../../cart/base/CartFindManyArgs";
import { Cart } from "../../cart/base/Cart";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { ReviewFindManyArgs } from "../../review/base/ReviewFindManyArgs";
import { Review } from "../../review/base/Review";
import { FoodService } from "../food.service";
@graphql.Resolver(() => Food)
export class FoodResolverBase {
  constructor(protected readonly service: FoodService) {}

  async _foodsMeta(
    @graphql.Args() args: FoodCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Food])
  async foods(@graphql.Args() args: FoodFindManyArgs): Promise<Food[]> {
    return this.service.foods(args);
  }

  @graphql.Query(() => Food, { nullable: true })
  async food(@graphql.Args() args: FoodFindUniqueArgs): Promise<Food | null> {
    const result = await this.service.food(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Food)
  async createFood(@graphql.Args() args: CreateFoodArgs): Promise<Food> {
    return await this.service.createFood({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Food)
  async updateFood(@graphql.Args() args: UpdateFoodArgs): Promise<Food | null> {
    try {
      return await this.service.updateFood({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Food)
  async deleteFood(@graphql.Args() args: DeleteFoodArgs): Promise<Food | null> {
    try {
      return await this.service.deleteFood(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Cart], { name: "carts" })
  async findCarts(
    @graphql.Parent() parent: Food,
    @graphql.Args() args: CartFindManyArgs
  ): Promise<Cart[]> {
    const results = await this.service.findCarts(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Order], { name: "orders" })
  async findOrders(
    @graphql.Parent() parent: Food,
    @graphql.Args() args: OrderFindManyArgs
  ): Promise<Order[]> {
    const results = await this.service.findOrders(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Review], { name: "reviews" })
  async findReviews(
    @graphql.Parent() parent: Food,
    @graphql.Args() args: ReviewFindManyArgs
  ): Promise<Review[]> {
    const results = await this.service.findReviews(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
