/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserAddressService } from "../userAddress.service";
import { UserAddressCreateInput } from "./UserAddressCreateInput";
import { UserAddress } from "./UserAddress";
import { UserAddressFindManyArgs } from "./UserAddressFindManyArgs";
import { UserAddressWhereUniqueInput } from "./UserAddressWhereUniqueInput";
import { UserAddressUpdateInput } from "./UserAddressUpdateInput";

export class UserAddressControllerBase {
  constructor(protected readonly service: UserAddressService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserAddress })
  async createUserAddress(
    @common.Body() data: UserAddressCreateInput
  ): Promise<UserAddress> {
    return await this.service.createUserAddress({
      data: data,
      select: {
        address: true,
        city: true,
        createdAt: true,
        id: true,
        updatedAt: true,
        user: true,
        zipCode: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [UserAddress] })
  @ApiNestedQuery(UserAddressFindManyArgs)
  async userAddresses(@common.Req() request: Request): Promise<UserAddress[]> {
    const args = plainToClass(UserAddressFindManyArgs, request.query);
    return this.service.userAddresses({
      ...args,
      select: {
        address: true,
        city: true,
        createdAt: true,
        id: true,
        updatedAt: true,
        user: true,
        zipCode: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserAddress })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async userAddress(
    @common.Param() params: UserAddressWhereUniqueInput
  ): Promise<UserAddress | null> {
    const result = await this.service.userAddress({
      where: params,
      select: {
        address: true,
        city: true,
        createdAt: true,
        id: true,
        updatedAt: true,
        user: true,
        zipCode: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserAddress })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUserAddress(
    @common.Param() params: UserAddressWhereUniqueInput,
    @common.Body() data: UserAddressUpdateInput
  ): Promise<UserAddress | null> {
    try {
      return await this.service.updateUserAddress({
        where: params,
        data: data,
        select: {
          address: true,
          city: true,
          createdAt: true,
          id: true,
          updatedAt: true,
          user: true,
          zipCode: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserAddress })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUserAddress(
    @common.Param() params: UserAddressWhereUniqueInput
  ): Promise<UserAddress | null> {
    try {
      return await this.service.deleteUserAddress({
        where: params,
        select: {
          address: true,
          city: true,
          createdAt: true,
          id: true,
          updatedAt: true,
          user: true,
          zipCode: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
